spring.application.name=FoodStore
spring.datasource.url=jdbc:postgresql://localhost:5432/foodstore
# Use environment variables for credentials in production. Set DB_USERNAME and DB_PASSWORD in your environment.
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123qwe&&}
spring.jpa.hibernate.ddl-auto=update
server.port=8080
file.upload-dir=uploads
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# Email (Gmail SMTP)
app.mail.fallback-username=yursunovxojiakbar53@gmail.com
app.mail.fallback-password=glmeopptrpimmtcq
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:${app.mail.fallback-username}}
spring.mail.password=${MAIL_PASSWORD:${app.mail.fallback-password}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8


# Telegram Bot (set TELEGRAM_BOT_TOKEN and TELEGRAM_BOT_USERNAME in env)
telegram.bot.token=${TELEGRAM_BOT_TOKEN:7785775650:AAFF-colhWxj-HW5vz3wAeGT6CcJy2Kovmw}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:t.me/Food_storeN1_bot}
telegram.bot.enabled=${TELEGRAM_BOT_ENABLED:true}
telegram.bot.admin-chat-ids=${TELEGRAM_ADMIN_CHAT_IDS:}
telegram.bot.page-size=5
telegram.bot.backend-base-url=http://localhost:8080
# Logging
